### PR TITLE
feat: Node 20 Support

### PR DESCRIPTION
**Pull request by djnew**
Hey @artmizu,

I took the liberty to update all dependencies, including @msw/interceptors, corrected the types, to support node 20

Have a nice day,

### CODE REVIEW

**Comment by artmizu** [comment]
@djnew hi, thank you for the participation!

the code in a MR is fine, but would you kindly check the lint, test and other stages? also check conflicting files please

**Comment by djnew** [comment]
@artmizu hi
I resolved conflicts and fix rerun tests, lints, please check this PR

**Comment by artmizu** [comment]
@djnew unfortunately requests calculation time doesn't measured properly 
image

could you check for additional details? https://github.com/artmizu/nuxt-prometheus/pull/15

**Comment by artmizu** [comment]
@djnew  also i have plenty amount of strange eslint errors without .eslintrc file:
image

image

**Comment by djnew** [comment]
@artmizu i changed .eslintrc file to eslint.config.js you may need to edit the settings? old .eslintrc file not worked after update packages 
I tried to save the eslint settings in a new file
image

**Comment by djnew** [comment]
I tried to configure eslint on vscode. eslint does not show errors when the "eslint.experimental.useFlatConfig" flag is enabled: true

image
image
image

**Pull request closed without merging**
