### PR TITLE
feat: Node 18 Support

### PR DESCRIPTION
**Pull request by hoersamu**
Hey @artmizu,

i took the liberty to update all dependencies including @mw@mswjs/interceptors since they implemented Node 18 support.

Have a nice day,
Samu

### CODE REVIEW

**Comment by artmizu** [comment]
hello @hoersamu 
thank you for participations

would you kindly fix the pipelines? all of it is broken, also you can test it localy

also i'm not sure about this changes, do we really need this packages?
image

**Comment by hoersamu** [comment]
Sure i will take a look. Sorry for missing to check the actions, it was a late night coding session for me yesterday. :+1:

**Comment by hoersamu** [comment]
Sorry for the long wait. I'll try to get to it this weekend. I actually run my Node 18 version in on of our services and noticed that the api request time is always zero. Is that a known bug or did i introduce it during my update?

**Comment by artmizu** [comment]
@hoersamu 

Yes, it's known bug 

Actually it's a reason why we need update @mswjs/interceptors to the last version, because it's the bug from this package.

image

**Comment by hoersamu** [comment]
Should work now. But the interceptors are still not working. Probably because https://github.com/unjs/node-fetch-native is not working nicely with the interceptors

**Comment by artmizu** [comment]
> Should work now. But the interceptors are still not working. Probably because https://github.com/unjs/node-fetch-native is not working nicely with the interceptors

unfortunately it's not working

also i don't think that node-fetch-native is a root of the problem, because the problem is arised only on specific version of @mswjs/interceptors

**Comment by or2e** [comment]
hi ;)
great library!
I also encountered the same problem ;(

a temporary solution for myself:
- share `State` with a plugin:
```
export default defineNuxtPlugin((ctx) => {
    ...
    return {
        provide: {
            metricsState: state,
        },
    };
});
```
- use custom instance $fetch with manually specified interceptors (`composables/useApi`)
```
...
return $fetch.create({
        baseURL: config.public.api.baseURL,

        onRequest({ request, options }) {
            const path = withQuery(
                    joinURL(options.baseURL ?? '', request as string),
                    {
                        ...(options.query && options.query),
                    }
                );
            nuxtApp.$metricsState.requests[path] = {
                start: Date.now(),
                end: Date.now(),
            };
        },

        onResponse({ request }) {
            if (nuxtApp.$metricsState.requests[request as string]) {
                nuxtApp.$metricsState.requests[request as string].end =
                    Date.now();
            }
        },
        ...
```

the solution is not universal, we are waiting for [this feature](https://github.com/nuxt/nuxt/issues/14736)

<details>
  <summary>Result</summary>
  
  image
</details>

**Comment by or2e** [comment]
https://github.com/unjs/ofetch/issues/295

**Comment by Gonzo17** [comment]
Hey guys, what's the state of this? I do need Node 18 support to use this module since Node 16 and 17 already passed EOL. If help is needed, I can have a look on this next week.

**Comment by artmizu** [comment]
> Hey guys, what's the state of this? I do need Node 18 support to use this module since Node 16 and 17 already passed EOL. If help is needed, I can have a look on this next week.

hi
actually overall state is the same and issues the same too. You can try to fix issues that i mention above, i'll review you code and support you without any doubts.

**Comment by Gonzo17** [comment]
> > Hey guys, what's the state of this? I do need Node 18 support to use this module since Node 16 and 17 already passed EOL. If help is needed, I can have a look on this next week.
> 
> hi actually overall state is the same and issues the same too. You can try to fix issues that i mention above, i'll review you code and support you without any doubts.

Thanks for your response. I'll try to fix it next week and give you updates here :)

**Comment by Gonzo17** [comment]
@artmizu 
I did some work on this, but didn't fully solve it yet.

First of all, I've forked the repository myself instead of using the one in this pr: https://github.com/Gonzo17/nuxt-prometheus
The reasons are that some changes happened since this was forked and that I wanted to keep it clean. I literally only updated the dependency and adjusted the code that needed changes.

Tests and typechecks work in my fork. What doesn't work are the interceptors, which results in the `api request time` not being calculated. That only happens with Node 18 & 19. I've also tested it with Node 16 & 17, there the interceptors work. So I'm not sure if the linked issue from @or2e in `ofetch` is the problem. I debugged into it and found out that the initialization of the interceptors work and `https.get`/`https.request` are overridden. But I didn't find out why it works differently for different Node versions. Do you have any idea how we can proceed here?

**Comment by or2e** [comment]
@Gonzo17 
- for nuxt 3.8 minimum nodejs version = 18 (to the question of how you tested on node 16, 17)
- the problem in node 18 is most likely due to the inclusion of `undici` as a native fetch client. https://nodejs.org/en/blog/announcements/v18-release-announce#fetch-experimental 
try running the application with this nodejs flag: `--no-experimental-fetch`
- I would create a separate sandbox, with `ofetch` + `msw/interceptors`, `axios` + `msw/interceptors`, with different versions of node (including 20) to see what the cause is

**Comment by Gonzo17** [comment]
Hey @or2e , I didn't update to Nuxt 3.8 yet on this fork, that's why I also tested with Node versions before 18. Right now Nuxt version 3.6.5 is being used here.
Thans for your hints, I'll have a look at it and gather more information :)

**Comment by artmizu** [comment]
@Gonzo17 have you tried to update @mswjs/interceptors package? when i did investigation around the issue it's arised due to this package incompatibility with node 18

take a look https://github.com/mswjs/interceptors/releases/tag/v0.22.0

**Comment by Gonzo17** [comment]
@artmizu Yes, see here: https://github.com/Gonzo17/nuxt-prometheus/blob/main/package.json#L38
I updated to the latest version of `@mswjs/interceptors` which is `0.25.7`. The changes I made to the module are as minimal as possible: https://github.com/artmizu/nuxt-prometheus/compare/main...Gonzo17:nuxt-prometheus:main
I also played a bit around with updating Nuxt to `3.8.0` and updating other dependencies, but since that didn't solve the issue with the interceptor I decided not to push that yet to keep it clean. I guess that's a task to be done once we have a solution for this problem here.

**Comment by artmizu** [comment]
@Gonzo17 have you try to change interceptor preset to FetchInterceptor? I did some investigation around the issue in the mswjs/interceptors repository and i have found this one:
https://github.com/mswjs/interceptors/issues/159#issuecomment-1435196359
image

in total since node 18 this package doesn't support undici out of the box, but they added this one as a separate preset, it's about global fetch and so: https://github.com/mswjs/msw/pull/1543

**Comment by artmizu** [comment]
also this one is import to get the main idea around the issue
image

**Comment by artmizu** [comment]
Hello guys 
A little while published the update with the latest Nuxt version support, the update also supported LTS version of Node.JS

One issue is still taking the place, but I'll try to solve it separately: https://github.com/artmizu/nuxt-prometheus/issues/42

@Gonzo17 @or2e @hoersamu

**Pull request closed without merging**
